// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJLLNn3PG4yHn0vv7pxxzEJWgOoaztaI',
    appId: '1:130019319095:web:b96ca95a537ae1931b0eb2',
    messagingSenderId: '130019319095',
    projectId: 'noisetime-youth',
    authDomain: 'noisetime-youth.firebaseapp.com',
    storageBucket: 'noisetime-youth.firebasestorage.app',
    measurementId: 'G-RVX1C1EZM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGPUbl4Ob6Argz-0jfFlRHZDXDBCtMhgI',
    appId: '1:130019319095:android:e5e27f0ac63473a71b0eb2',
    messagingSenderId: '130019319095',
    projectId: 'noisetime-youth',
    storageBucket: 'noisetime-youth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLFY2bFd1Cep99nDJiEMvpB5KAq6SqqLM',
    appId: '1:130019319095:ios:a36de4222f6f0edf1b0eb2',
    messagingSenderId: '130019319095',
    projectId: 'noisetime-youth',
    storageBucket: 'noisetime-youth.firebasestorage.app',
    iosClientId: '130019319095-snklir9b495sjk6oj5ku08bm6i2fnba4.apps.googleusercontent.com',
    iosBundleId: 'com.akzmft8282.project.noisetime',
  );
}
